Repository mnxmnz/colfume-frontend, pull requests merged in 2021-08, with the labels that each got.

#231 Feat/test/question
  components/common/Footer.tsx
  components/common/MobileFooter.tsx
  components/common/NewFooter.tsx
  components/test/results/CopyLinkBtn.tsx
  lib/api/client.ts
  lib/api/detail/detail.ts
  lib/api/main/getFilter.ts
  lib/api/main/getRecomm.ts
  lib/api/product/getProduct.ts
  lib/api/search/getFilter.ts
  lib/api/search/search.ts
  lib/api/test/getAnswer.ts
  lib/api/test/postAnswer.ts
  pages/_document.tsx
Labels: 민지

#233 Feat/search
  assets/index.ts
  assets/main/MobileMenuIcon.svg
  components/common/Header.tsx
  components/common/MobileHeader.tsx
  components/index.ts
Labels: 영서

#234 feat: 테스트 완료 링크 공유 여부에 따라 로딩뷰 생성
  components/test/questions/Loading.tsx
  components/test/results/CopyLinkBtn.tsx
  components/test/results/ResultButton.tsx
  components/test/results/TestResult.tsx
Labels: 민지

#235 [Header] mobile header
  assets/index.ts
  assets/main/MenuIcon.svg
  components/common/MobileHeader.tsx
Labels: 영서

#236 fix: type error
  components/common/MobileHeader.tsx
Labels: 영서

#244 [Search] 반응형
  components/common/Header.tsx
  components/common/MobileHeader.tsx
  components/search/SearchBar.tsx
  components/search/SearchWrap.tsx
  components/search/SelectKeyword.tsx
Labels: 영서

#246 chore: product detail img 크기 수정
  components/productDetail/Filter.tsx
  components/productDetail/ProductDetailWrap.tsx
  components/productDetail/ProductInfo.tsx
Labels: 민지

#250 Feat/main/recomm
  components/main/Recommendation.tsx
Labels: 소령

#265 Feat/main/mobile/soryeongk
  components/productDetail/Filter.tsx
  components/productDetail/ProductDetailWrap.tsx
  components/productDetail/ProductInfo.tsx
Labels: 소령

#269 Feat/main/mobile/soryeongk
  components/main/Banner.tsx
  components/main/Recommendation.tsx
  components/productDetail/Description.tsx
  components/productDetail/Filter.tsx
  components/search/SearchBar.tsx
Labels: 소령

#271 style: fix position of search bar
  components/search/SearchBar.tsx
Labels: 소령

#273 chore: del position relative
  components/search/SearchBar.tsx
Labels: 소령

#274 style: fix position of search bar(2)
  components/search/SearchBar.tsx
Labels: 영서

#282 solve rebase conflicts
  components/test/results/MatchingColor1.tsx
Labels: 소령

#283 style: header, search 반응형 수정
  components/common/Header.tsx
  components/common/MobileHeader.tsx
  components/search/PerfumeImg.tsx
  components/search/SearchBar.tsx
  components/search/SelectKeyword.tsx
Labels: 영서

#284 fix: keyword 필터 해제 오류
  components/search/SelectKeyword.tsx
Labels: 영서

#285 Feat/main/mobile/soryeongk
  components/test/results/MatchingColor1.tsx
  components/test/results/MatchingColor2.tsx
  components/test/results/ResultTitle.tsx
Labels: 소령

#286 refactor: del doubled codes
  components/search/SelectKeyword.tsx
Labels: 소령

#290 feat: mobile view deselecting when clicked
  components/search/SelectKeyword.tsx
Labels: 소령

#293 style: header css 수정 및 search bar icon mobile 수정
  components/common/Header.tsx
  components/search/SearchBar.tsx
Labels: 영서

#297 style: mobile header click event add
  components/common/MobileHeader.tsx
Labels: 영서

#302 Feat/main/mobile/soryeongk
  components/main/Recommendation.tsx
  components/productDetail/ProductDetailWrap.tsx
  components/search/PerfumeImg.tsx
  components/test/results/MatchingColor1.tsx
  components/test/results/MobileResult.tsx
  components/test/results/TestResult.tsx
  lib/api/detail/detail.ts
  pages/product/[id].tsx
  states/detail.ts
Labels: 소령
